config/routes.rb
Rails.application.routes.draw do
    resources :pics

    root 'pics#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pic.rb
class Pic < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  def index
    @pics = Pic.all
  end

  def new
    @pic = Pic.new
  end

  def create
    @pic = Pic.new(params.require(:pic).permit(:image))
    @pic.save
    redirect_to @pic
  end

  def edit
  end

  def show
    @pic = Pic.find(params[:id])
  end

  def update
  end

  def destroy
  end
  
  
  # private
  #
  # def pic_params
  #   params.require(:pic).permit(:image)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'Rimgur', root_path, class: 'navbar-brand' %>
      <%= link_to 'New Post', new_pic_path, class: 'navbar-brand' %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails5image</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://bootswatch.com/paper/bootstrap.min.css">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pics/_form.html.erb
<%= form_for @pic do |f| %>
  <%= f.label :image do %>
    <%=	f.hidden_field :image_cache %>
    <%=	f.file_field :image %>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/pics/index.html.erb
<% @pics.each do |pic| %>
    <%=	image_tag(pic.image.url, width: '100%', crop: "scale")  %>
<% end %>

app/views/pics/new.html.erb
<%= render 'pics/form' %>

app/views/pics/show.html.erb
<%=	image_tag(@pic.image.url, width: '100%', crop: "scale") %>

<p class="text-center"><%= link_to 'Home', root_path %></p>